baseURL = "https://chrome-web-store.higamaya.com/"
languageCode = "en-us"
title = "Higama-ya CWS"
publishDir = "docs"
enableRobotsTXT = true

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'

[params]
description = "Higama-ya's website for Chrome Web Store"

[params.logo]
url = "/images/logo_192x192.png"
type = "image/png"
width = 192
height = 192

[author]
name = "Mitsunobu Yoneda"
github_url = "https://github.com/higamaya"
twitter_url = "https://twitter.com/higama_ya"
email = "support@higamaya.com"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Items"
url = "/items/"
weight = 2

[[menu.main]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 3
